// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int32
	Name string
	Bio  pgtype.Text
}

type Book struct {
	ID          int32
	AuthorID    pgtype.Int4
	Name        string
	Description pgtype.Text
}
